/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package valida;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class FrmValida extends javax.swing.JFrame {

    /**
     * Creates new form FrmValida
     */
    public FrmValida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValida = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnValida.setText("VALIDA");
        btnValida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidaActionPerformed(evt);
            }
        });

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValida)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnValida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidaActionPerformed
        // TODO add your handling code here:
      String x = txtCedula.getText();
      Boolean y = ValidaCedula.validacionCedula(x);
        //ValidaCedula.validacionCedula("1713647642");
      //System.out.println(y);
       if (y==true)
        System.out.println("Correcto");
        //JOptionPane.showMessageDialog(null, "Escribe algo", "Escribe algo", JOptionPane.WARNING_MESSAGE);
         else
        //System.out.println("Incorrecto");
           JOptionPane.showMessageDialog(null, "Cedula Incorrecta", "Validador", JOptionPane.WARNING_MESSAGE);

       Conexion c = new Conexion();
       Connection con = c.mkConection();
       
       if(con == null){ 
                //Error al establecer la conexión
                 System.out.println("Conexion no establecida");
                }
       else {
            try { 
                ResultSet rs = null; 

                 Statement stm = con.createStatement(); 

                 //String strSQL = "SELECT * FROM dba.employee where empnum = '"+999+"'"; 
                 //String strSQL = "SELECT * FROM dba.member where memcode = '"+4196310+"'";
                 String strSQL = "SELECT * FROM dba.member where memcode like '%" + 419631 + "%'";
                 //Ejecuta la consulta SQL
                 rs = stm.executeQuery(strSQL);  
               
                 //Trabajar con el result set…  
         String cedula = null;
         String nombre = null;
         String apellido = null;
         
                 while (rs.next())
         {
               nombre= rs.getString(3);
               apellido = rs.getString(4);
               cedula = rs.getString(13);
               
String m = cedula.substring(3, 13);
                                System.out.println(nombre);
                                System.out.println(apellido);
                                System.out.println(cedula);
                                System.out.println(m);
         }
//                 String m = cedula.substring(3, 13);
//                                System.out.println(nombre);
//                                System.out.println(apellido);
//                                System.out.println(cedula);
//                                System.out.println(m);
                                
//                                      Boolean t = ValidaCedula.validacionCedula(m);
//        //ValidaCedula.validacionCedula("1713647642");
//      //System.out.println(y);
//       if (t==true)
//        System.out.println("Correcta");
//        //JOptionPane.showMessageDialog(null, "Escribe algo", "Escribe algo", JOptionPane.WARNING_MESSAGE);
//         else
//        System.out.println("Incorrecta");
                                
                 //Cerrar todo
                 rs.close(); 

                 stm.close(); 

                 boolean isClosed = c.closeConecction();

                 if(!isClosed){ 

                   //Error al cerrar la conexión
                 }
            } catch (SQLException ex) {
                Logger.getLogger(FrmValida.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       
    }//GEN-LAST:event_btnValidaActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmValida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmValida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmValida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmValida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmValida().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValida;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
